version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "de:04:2d:f5:eb:92:09:ea:18:b3:8c:39:65:85:7d:ae"
      - checkout
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Build index
          command: yarn export
      - run:
          name: Stage changes
          command: |
            git config --global user.email "alexashley15@gmail.com"
            git config --global user.name "Alex Ashley"
            git add .
      - run:
          name: Commit and push site
          command: |
            git commit -m "[skip ci] Build tiddlywiki"
            git push origin master
      - when:
          condition: git diff-index --quiet HEAD